version: '3.8'

services:

  web:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php_container
    volumes:
      - ./app:/var/www/html